const Merkkiluettelo : any[] = [
    {
      "postimerkki_id": "1",
      "asiasanat": "soikiomerkki ovaali vaakuna postitorvi leijona kruunu 1856",
      "ilmestymispaiva": "01.03.1856",
      "kayton_paattyminen": "31.01.1860",
      "nimellisarvo": "0,05",
      "merkin_nimi": "Malli 1856 Soikiomerkki",
      "merkin_vari": "sininen",
      "painopaikka": "Leimakonttori",
      "painosmaara": "138500",
      "taiteilija": "",
      "valuutta": "rupla",
      "kuvan_url": "http://www.postimuseo.fi/kiosks/14/postimerkit/260x260/0001.jpg"
    },
    {
      "postimerkki_id": "2",
      "asiasanat": "soikiomerkki ovaali vaakuna postitorvi leijona kruunu 1856",
      "ilmestymispaiva": "01.03.1856",
      "kayton_paattyminen": "31.01.1860",
      "nimellisarvo": "0,10",
      "merkin_nimi": "Malli 1856 Soikiomerkki",
      "merkin_vari": "punainen",
      "painopaikka": "Leimakonttori",
      "painosmaara": "442431",
      "taiteilija": "",
      "valuutta": "rupla",
      "kuvan_url": "http://www.postimuseo.fi/kiosks/14/postimerkit/260x260/0002.jpg"
    },
    {
      "postimerkki_id": "3",
      "asiasanat": "vaakuna leijona kruunu isohampainen 1860",
      "ilmestymispaiva": "01.01.1860",
      "kayton_paattyminen": "31.12.1884",
      "nimellisarvo": "0,05",
      "merkin_nimi": "Malli 1860",
      "merkin_vari": "sininen",
      "painopaikka": "Senaatin kirjapaino",
      "painosmaara": "698000",
      "taiteilija": "",
      "valuutta": "rupla",
      "kuvan_url": "http://www.postimuseo.fi/kiosks/14/postimerkit/260x260/0003.jpg"
    },
    {
      "postimerkki_id": "4",
      "asiasanat": "vaakuna leijona kruunu 1860  isohampainen",
      "ilmestymispaiva": "01.01.1860",
      "kayton_paattyminen": "31.12.1884",
      "nimellisarvo": "0,10",
      "merkin_nimi": "Malli 1860",
      "merkin_vari": "punainen",
      "painopaikka": "Senaatin kirjapaino",
      "painosmaara": "1428160",
      "taiteilija": "",
      "valuutta": "rupla",
      "kuvan_url": "http://www.postimuseo.fi/kiosks/14/postimerkit/260x260/0004.jpg"
    },
    {
      "postimerkki_id": "5",
      "asiasanat": "vaakuna leijona kruunu 1866 isohampainen",
      "ilmestymispaiva": "01.01.1866",
      "kayton_paattyminen": "31.12.1884",
      "nimellisarvo": "0,05",
      "merkin_nimi": "Malli 1866",
      "merkin_vari": "ruskea / hailakanlila paperi",
      "painopaikka": "Senaatin kirjapaino",
      "painosmaara": "739000",
      "taiteilija": "",
      "valuutta": "markka",
      "kuvan_url": "http://www.postimuseo.fi/kiosks/14/postimerkit/260x260/0005.jpg"
    },
    {
      "postimerkki_id": "6",
      "asiasanat": "vaakuna leijona kruunu 1866 isohampainen",
      "ilmestymispaiva": "01.12.1866",
      "kayton_paattyminen": "31.12.1884",
      "nimellisarvo": "0,08",
      "merkin_nimi": "Malli 1866",
      "merkin_vari": "musta / vihreä paperi",
      "painopaikka": "Senaatin kirjapaino",
      "painosmaara": "925000",
      "taiteilija": "",
      "valuutta": "markka",
      "kuvan_url": "http://www.postimuseo.fi/kiosks/14/postimerkit/260x260/0006.jpg"
    },
    {
      "postimerkki_id": "7",
      "asiasanat": "vaakuna leijona kruunu 1866 isohampainen",
      "ilmestymispaiva": "01.01.1866",
      "kayton_paattyminen": "31.12.1884",
      "nimellisarvo": "0,10",
      "merkin_nimi": "Malli 1866",
      "merkin_vari": "musta / keltainen paperi",
      "painopaikka": "Senaatin kirjapaino",
      "painosmaara": "778500",
      "taiteilija": "",
      "valuutta": "markka",
      "kuvan_url": "http://www.postimuseo.fi/kiosks/14/postimerkit/260x260/0007.jpg"
    },
    {
      "postimerkki_id": "8",
      "asiasanat": "vaakuna leijona kruunu 1866 isohampainen",
      "ilmestymispaiva": "01.01.1866",
      "kayton_paattyminen": "31.12.1884",
      "nimellisarvo": "0,20",
      "merkin_nimi": "Malli 1866",
      "merkin_vari": "sininen",
      "painopaikka": "Senaatin kirjapaino",
      "painosmaara": "4569800",
      "taiteilija": "",
      "valuutta": "markka",
      "kuvan_url": "http://www.postimuseo.fi/kiosks/14/postimerkit/260x260/0008.jpg"
    },
    {
      "postimerkki_id": "9",
      "asiasanat": "vaakuna leijona kruunu 1866 isohampainen",
      "ilmestymispaiva": "01.01.1866",
      "kayton_paattyminen": "31.12.1884",
      "nimellisarvo": "0,40",
      "merkin_nimi": "Malli 1866",
      "merkin_vari": "punainen",
      "painopaikka": "Senaatin kirjapaino",
      "painosmaara": "3232500",
      "taiteilija": "",
      "valuutta": "markka",
      "kuvan_url": "http://www.postimuseo.fi/kiosks/14/postimerkit/260x260/0009.jpg"
    },
    {
      "postimerkki_id": "10",
      "asiasanat": "vaakuna leijona kruunu 1866 isohampainen",
      "ilmestymispaiva": "01.05.1867",
      "kayton_paattyminen": "31.12.1884",
      "nimellisarvo": "1",
      "merkin_nimi": "Malli 1866",
      "merkin_vari": "kellanruskea",
      "painopaikka": "Senaatin kirjapaino",
      "painosmaara": "86420",
      "taiteilija": "",
      "valuutta": "markka",
      "kuvan_url": "http://www.postimuseo.fi/kiosks/14/postimerkit/260x260/0010.jpg"
    }
]
    export default Merkkiluettelo;